version: 2.1
jobs:
  build:
      docker:
        - image: clamorisse/hugo:0.15
      working_directory: ~/mysite
      environment: 
          HUGO_BUILD_DIR: ~/mysite/public
      steps:
          # install git
        - run: sudo apt-get update && sudo apt-get install git
        - checkout
        
        - run: docker run -v $(pwd)/:/usr/src/blog clamorisse/hugo:0.15 hugo --baseUrl=http://localhost/
        #test
        - run: docker run -d -p 1313:1313 --name hugotest -v $(pwd)/:/usr/src/blog clamorisse/hugo:0.15 hugo server --baseUrl=http://localhost/ --watch --bind=0.0.0.0; sleep 10 
        - run: docker ps -a 
        - run: curl --retry 5 --retry-delay 5 -v http://localhost:1313 
        - run: docker logs hugotest 
        - run: if [ "$(ls -A ./public)" ]; then echo "generated public dir"; else exit 5; fi 
        - run: cat $(pwd)/public/index.html 
        - run: docker stop hugotest 
        - run: mv ./public/ ./old-public 


        
        #validate html
        - run:
            name: "Test Website"
            command: htmlproofer ~/mysite/public/ --allow-hash-href --check-html --empty-alt-ignore --disable-external

        # Deploy
  
        - deploy:
            name: deploy to AWS
            command: |
                if [[ "${CIRCLE_BRANCH}" == "master" ]]; then
                    # aws s3 sync public/ s3://pemazomkyi.com/ --delete           
                  else
                    echo "Not master branch, dry run only"
                fi
workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            branches:
              only: master
