version: 2.1
jobs:
  build:
      docker:
        - image: cibuilds/hugo:latest
      working_directory: ~/mysite
      environment: 
          HUGO_BUILD_DIR: ~/mysite/public
      steps:
         # install git
        - run: sudo apt-get update && sudo apt-get install git
        - checkout
        
        - run:
            name: "Install AWS CLI( first install pip, the python package manager)"
            command: sudo apt-get install awscli

        # build with Hugo Server     
        - run:
            name: "Run Hugo"
            command: HUGO_ENV=production hugo -v -d ~/mysite/public
        
       
        # Deploy
  
        - deploy:
            name: deploy to AWS
            command: |
                if [[ "${CIRCLE_BRANCH}" == "firstbranch" ]]; then
                     aws s3 sync public/ s3://pemazomkyi.com/ --delete           
                  else
                    echo "Not master branch, dry run only"
                fi

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            branches:
              only: firstbranch
