version: 2.1
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/mysite
    environment: 
        HUGO_BUILD_DIR: ~/mysite/public
    steps:
       # install git
      - run: sudo apt-get update && sudo apt-get install -y --no-install-recommends git
      - checkout

      # install git submodules for managing third-party dependencies
      # - run: git submodule sync && git submodule update --init
      

      - run:
          name: "Install AWS CLI( first install pip, the python package manager)"
          command: |
            sudo apt-get install awscli

      # build with Hugo      
      - run:
          name: "Run Hugo"
          command: HUGO_ENV=production hugo -v -d ~/mysite/public
      #      
      #- run:
      #    name: "Test Website"
      #    command: htmlproofer ~/mysite/public/ --allow-hash-href --check-html --empty-alt-ignore --disable-external

      # Deploy
      # aws s3 sync public/ s3://pemazomkyi.com/ --delete   

      - deploy:
          name: deploy to AWS
          command: |
              if [[ "${CIRCLE_BRANCH}" == "master" ]]; then
                  aws s3 sync public/ s3://pemazomkyi.com/ --delete           
                else
                  echo "Not master branch, dry run only"
              fi